### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by Sorna210** [deshpandenu/Time-Series-Forecasting-of-Amazon-Stock-Prices-using-Neural-Networks-LSTM-and-GAN-#3]
Where are the sources for the data mentioned in the sentimental analysis component?Can you please give a brief on that?

**Comment by deshpandenu** [comment]
You may have to look at datasources like Kaggle or open stock data sources and scrape data or use an API. I used both. I think something similar to this is there somewhere on Kaggle.
